package es.yisus.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

import es.yisus.dbcontext.DBContext;
import es.yisus.modelo.Game;
import es.yisus.modelo.User;

public class GameDAO {

	public static List<Game> getGames() throws SQLException {
		List<Game> retrievedGames = new ArrayList<>();
		String sqlGame = "SELECT * FROM games";
		String sqlUser = "SELECT * FROM users WHERE id = ?";
		try (Connection con = DBContext.getConnection();
				Statement stGame = con.createStatement();
				PreparedStatement psUser = con.prepareStatement(sqlUser)) {
			try (ResultSet rsGame = stGame.executeQuery(sqlGame)) {
				while (rsGame.next()) {
					Game game = new Game();
					game.setId(rsGame.getInt("id"));
					game.setScore(rsGame.getInt("score"));
					game.setFinished(rsGame.getInt("finished") == 1);
					psUser.setInt(1, rsGame.getInt("user_id"));
					try (ResultSet rsUser = psUser.executeQuery()) {
						if (rsUser.next()) {
							User user = new User();
							user.setId(rsUser.getInt("id"));
							user.setNickname(rsUser.getString("nickname"));
							game.setUser(user);
						}
					}
					String dateTime = rsGame.getString("date_time");
					if (dateTime != null) {
						try {
							game.setDateTime(LocalDateTime.parse(dateTime.replace(" ", "T")));
						} catch (DateTimeParseException e) {
							System.err
									.println("Error parsing date and time. Current date and time will be used instead");
							game.setDateTime(LocalDateTime.now());
						}
					}
					retrievedGames.add(game);
				}
			}
		}

		return retrievedGames;
	}

	public static Game getGame(int id) throws SQLException {
		String sqlGame = "SELECT * FROM games WHERE id = ?";
		String sqlUser = "SELECT * FROM users WHERE id = ?";
		Game game = null;
		try (Connection con = DBContext.getConnection();
				PreparedStatement psGame = con.prepareStatement(sqlGame);
				PreparedStatement psUser = con.prepareStatement(sqlUser)) {
			psGame.setInt(1, id);
			try (ResultSet rsGame = psGame.executeQuery()) {
				if (rsGame.next()) {
					game = new Game();
					game.setId(rsGame.getInt("id"));
					game.setScore(rsGame.getInt("score"));
					game.setFinished(rsGame.getInt("finished") == 1);
					psUser.setInt(1, rsGame.getInt("user_id"));
					try (ResultSet rsUser = psUser.executeQuery()) {
						if (rsUser.next()) {
							User user = new User();
							user.setId(rsUser.getInt("id"));
							user.setNickname(rsUser.getString("nickname"));
							game.setUser(user);
						}
					}
					String dateTime = rsGame.getString("date_time");
					if (dateTime != null) {
						try {
							game.setDateTime(LocalDateTime.parse(dateTime.replace(" ", "T")));
						} catch (DateTimeParseException e) {
							System.err
									.println("Error parsing date and time. Current date and time will be used instead");
							game.setDateTime(LocalDateTime.now());
						}
					}
				}
			}
		}
		return game;
	}

	public static int deleteGame(int id) throws SQLException {
		int deleted = 0;
		String sqlDelete = "DELETE FROM games WHERE id = ?";
		try (Connection con = DBContext.getConnection(); PreparedStatement ps = con.prepareStatement(sqlDelete)) {
			ps.setInt(1, id);
			deleted = ps.executeUpdate();
		}
		return deleted;
	}

	public static int updateGame(Game game) throws SQLException {
		String sqlUpdate = "UPDATE games SET user_id = ?, score = ?, finished = ? WHERE id = ?";
		int updated = 0;
		try (Connection con = DBContext.getConnection(); PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
			ps.setInt(1, game.getUser().getId());
			ps.setInt(2, game.getScore());
			ps.setInt(3, game.isFinished() ? 1 : 0);
			ps.setInt(4, game.getId());
			updated = ps.executeUpdate();
		}
		return updated;
	}

	public static int updateGame(Game game, Connection con) throws SQLException {
		String sqlUpdate = "UPDATE games SET user_id = ?, score = ?, finished = ? WHERE id = ?";
		int updated = 0;
		try (PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
			ps.setInt(1, game.getUser().getId());
			ps.setInt(2, game.getScore());
			ps.setInt(3, game.isFinished() ? 1 : 0);
			ps.setInt(4, game.getId());
			updated = ps.executeUpdate();
		}
		return updated;
	}

	public static int insertGame(Game game) throws SQLException {
		String sqlInsertGame = "INSERT INTO games(user_id, score, finished) VALUES (?, ?, ?)";
		int inserted = 0;
		try (Connection con = DBContext.getConnection();
				PreparedStatement psGame = con.prepareStatement(sqlInsertGame, Statement.RETURN_GENERATED_KEYS)) {
			psGame.setInt(1, game.getUser().getId());
			psGame.setInt(2, game.getScore());
			psGame.setInt(3, game.isFinished() ? 1 : 0);
			psGame.executeUpdate();
			// Autogenerated key is brought back from DB
			try (ResultSet rs = psGame.getGeneratedKeys()) {
				if (rs.next()) {
					game.setId(rs.getInt(1)); // Autogenerated ID is set to Game
				}
			}
		}
		return inserted;
	}

	public static int insertGame(Game game, Connection con) throws SQLException {
		String sqlInsertGame = "INSERT INTO games(user_id, score, finished) VALUES (?, ?, ?)";
		int inserted = 0;
		try (PreparedStatement psGame = con.prepareStatement(sqlInsertGame, Statement.RETURN_GENERATED_KEYS)) {
			psGame.setInt(1, game.getUser().getId());
			psGame.setInt(2, game.getScore());
			psGame.setInt(3, game.isFinished() ? 1 : 0);
			psGame.executeUpdate();
			// Autogenerated key is brought back from DB
			try (ResultSet rs = psGame.getGeneratedKeys()) {
				if (rs.next()) {
					game.setId(rs.getInt(1)); // Autogenerated ID is set to Game
				}
			}
		}
		return inserted;
	}

}
