<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>es.dam1</groupId>
  <artifactId>GestorTareas</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>GestorTareas</name>
  <description>GestorTareas</description>
  <properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<maven.compiler.release>26</maven.compiler.release> <!-- Versión de la JDK que quiero usar -->
	<javafx.version>26</javafx.version> <!-- Esta versión debe coincidir en principio con la del compilador de la línea justo encima -->
  </properties>
  <!-- Librerías que necesita mi proyecto. Las he copiado del pom de la profe -->
  <dependencies>
  	<dependency>
		<groupId>org.openjfx</groupId>
		<artifactId>javafx-controls</artifactId>
		<version>${javafx.version}</version>
	</dependency>
	<dependency>
		<groupId>org.openjfx</groupId>
		<artifactId>javafx-fxml</artifactId>
		<version>${javafx.version}</version>
	</dependency>
  
  </dependencies>
  
  <build>
  <!-- Este plugin y su configuración los he copiado del pom de la profe -->
	<plugins>
		<plugin> <!-- Este plugin de javafx es necesario para poder ejecutar la app, dado que no puede correrse con un Run As Java Application -->
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-maven-plugin</artifactId>
			<version>0.0.8</version>
			<configuration>
				<!-- Aquí es necesario poner cuál es la clase principal (con el main) de mi aplicación -->
				<mainClass>es.dam1.app.GestorTareas</mainClass>
				<!-- Aquí es necesario poner la ruta a mi JDK. Esto es opcional si sólo tenemos un JDK -->
				<executable>C:\Program Files\Java\jdk-26\bin\java.exe</executable>
			</configuration>
		</plugin>
	</plugins>
  </build>
</project>